version: '3.8'
services:
  app-node:
    image: grocery-store-app
    build: .
    container_name: app-node
    ports:
      - "3000:3000"
    volumes: # adding these volumes to our docker filesystem enables hot-reloading for the dev server
    - ./pages:/app/pages
    - ./public:/app/public
    - ./styles:/app/styles