import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import SearchForProducts from '../components/SearchForProducts'
import Navbar from '../components/Navbar'

const Home: NextPage = ({data}: any) => {
  return (
    <div className='flex flex-col justify-center items-center bg-gray-300 h-screen'>
      <div className='relative bottom-6 h-1/6 shadow'>
        <Navbar/>
      </div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="flex flex-row justify-center items-center h-5/6 w-screen">
          <SearchForProducts/> 
      </div>
    </div>
  )
}


export async function getServerSideProps() {

  const {data} = await axios.get('http://localhost:3000/api/hello')

  return {
    props: {
      data
    }
  }
}

export default Home
